require "pea.utils"

lvim:set {
    dev_mode = true,
    leader = "space",
    format_on_save = true,
    lsp = require "pea.lsp",
    keys = require "pea.keys",
    transparent_window = true,
    icons = require "pea.icons",
    colorscheme = "one_monokai",
    plugins = require "pea.plugins",
    options = require "pea.options",
    autocommands = require "pea.autocommands",
    builtin = {
        cmp = require "pea.builtin.cmp",
        lir = require "pea.builtin.lir",
        alpha = require "pea.builtin.alpha",
        mason = require "pea.builtin.mason",
        notify = require "pea.builtin.notify",
        lualine = require "pea.builtin.lualine",
        terminal = require "pea.builtin.terminal",
        nvimtree = require "pea.builtin.nvimtree",
        autopairs = require "pea.builtin.autopairs",
        which_key = require "pea.builtin.which_key",
        telescope = require "pea.builtin.telescope",
        treesitter = require "pea.builtin.treesitter",
        illuminate = require "pea.builtin.illuminate",
        bufferline = require "pea.builtin.bufferline",
        indentlines = require "pea.builtin.indentlines",
        breadcrumbs = require "pea.builtin.breadcrumbs",
    },
}
