name: install-config

on:
  push:
    branches:
      - "main"
      - "test/ci"
    paths:
      - ".github/workflows/**"
      - "lua/**"

jobs:
  unix:
    name: ${{ matrix.os }} ${{ matrix.runner }} (${{ matrix.neovim }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            os: Linux
            neovim: v0.7.0
          - runner: ubuntu-22.04
            os: Linux
            neovim: nightly
          - runner: macos-latest
            os: OS X
            neovim: v0.7.0
          - runner: macos-12
            os: OS X
            neovim: nightly
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@main
      - name: Install neovim
        env:
          RELEASE_VER: ${{ matrix.neovim }}
        run: | 
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          bash <(curl -s https://raw.githubusercontent.com/LunarVim/LunarVim/rolling/utils/installer/install-neovim-from-release)
      - name: Install config
        timeout-minutes: 5
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          bash ./utils/install.sh
